import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

/// Shown on the licenses page under the app's own name.
const appLegalese =
    'Copyright 2026 stonetech\n\n'
    'Docudis is free software under the GNU Affero General Public License, '
    'version 3, and comes with no warranty. Source code: '
    'https://github.com/stonetech-pxia/docudis-desktop';

/// Adds the notices Flutter does not collect by itself (native libraries,
/// Rust crates, fonts, the model) to the licenses page. The list is
/// generated by tool/generate_licenses.py.
void registerBundledLicenses() {
  LicenseRegistry.addLicense(() async* {
    final entries = jsonDecode(
      await rootBundle.loadString('assets/licenses/licenses.json'),
    ) as List<dynamic>;
    for (final entry in entries.cast<Map<String, dynamic>>()) {
      yield LicenseEntryWithLineBreaks(
        (entry['packages'] as List<dynamic>).cast<String>(),
        entry['text'] as String,
      );
    }
  });
}
